version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    command: yarn start
    volumes:
      - .:/app:cached
  test:
    image: karakurifarmweb_web
    command: yarn test
    volumes:
      - .:/app:cached
