version: '3'

services:
  web:
    build: ./docker_files/web/
    ports:
      - "3000:3000"
    command: yarn start
    volumes:
      - .:/app:cached
  test:
    image: karakurifarmweb_web
    command: yarn test
    volumes:
      - .:/app:cached
  deployment-staging:
    build: ./docker_files/deployment/
    env_file: ./aws_secrets.env
    command: yarn deploy-to-staging
    volumes:
      - .:/app:cached
  deployment-production:
    build: ./docker_files/deployment/
    env_file: ./aws_secrets.env
    command: yarn deploy-to-production
    volumes:
      - .:/app:cached
