version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    command: npm start
    environment:
      - ENV NPM_CONFIG_LOGLEVEL=warn
    volumes:
      - .:/app:cached
  test:
    image: karakurifarmweb_web
    command: npm test
    environment:
      - ENV NPM_CONFIG_LOGLEVEL=warn
    volumes:
      - .:/app:cached
