version: 2.1
executors:
  builder:
    docker:
      - image: circleci/node:8.10.0
    working_directory: ~/repo
  deployer:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
commands:
  restore_yarn:
    steps:
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-
  save_yarn:
    steps:
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
  persist:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - .
  attach:
    steps:
      - attach_workspace:
          at: .
  set_env:
    # context: Karakuri-Farm-xxx を指定すること！
    parameters:
      environment_tmp_env_name:
        type: enum
        enum: ["test", "staging-env", "production-env"]
    steps:
      - run:
          name: Set Env << parameters.environment_tmp_env_name >>
          command: |
            TMP_LOCAL_ENV_FILENAME=".env.<< parameters.environment_tmp_env_name >>.local"
            echo "" > ${TMP_LOCAL_ENV_FILENAME}
            echo "REACT_APP_COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}" >> ${TMP_LOCAL_ENV_FILENAME}
            echo "REACT_APP_COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}" >> ${TMP_LOCAL_ENV_FILENAME}

jobs:
  install:
    executor:
      name: builder
    steps:
      - checkout
      - restore_yarn
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_yarn
      - persist

  test:
    # context: Karakuri-Farm-xxx を指定すること！
    executor:
      name: builder
    steps:
      - attach
      - set_env:
          environment_tmp_env_name: test
      - run:
          name: Test
          command: yarn test

  build:
    # context: Karakuri-Farm-xxx を指定すること！
    executor:
      name: builder
    parameters:
      environment:
        type: enum
        enum: ["staging", "production"]
    steps:
      - attach
      - set_env:
          environment_tmp_env_name: << parameters.environment >>-env
      - run:
          name: Build to << parameters.environment >>
          command: |
            TMP_SH_NAME="deploy-to-<< parameters.environment >>-build.sh"
            sh ${TMP_SH_NAME}
      - persist

  deploy:
    executor:
      name: deployer
    parameters:
      environment:
        type: enum
        enum: ["staging", "production"]
    steps:
      - attach
      - run:
          name: 'Install Deploy Tools'
          command: |
            pip3 install --upgrade --user awscli
            echo 'export PATH=~/.local/bin:$PATH' > ~/.profile
            source ~/.profile
            aws configure set preview.cloudfront true
      - run:
          name: Deploy to << parameters.environment >>
          command: |
            source ~/.profile
            TMP_SH_NAME="deploy-to-<< parameters.environment >>-deploy.sh"
            sh ${TMP_SH_NAME}

workflows:
  setup_and_deploy:
    jobs:
      - install
      - test:
          context: Karakuri-Farm-development
          requires:
            - install
      - build:
          name: build_to_staging
          context: Karakuri-Farm-staging
          environment: staging
          requires:
            - install
            - test
      - deploy:
          name: deploy_to_staging
          environment: staging
          requires:
            - build_to_staging
          filters:
            branches:
              only: master
      - approval_to_production:
          type: approval
          requires:
            - install
            - test
          filters:
            branches:
              only: master
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}.*/
      - build:
          name: build_to_production
          context: Karakuri-Farm-production
          environment: production
          requires:
            - approval_to_production
      - deploy:
          name: deploy_to_production
          environment: production
          requires:
            - build_to_production
