version: 2.1
executors:
  builder:
    docker:
      - image: circleci/node:8.9.0-alpine
    working_directory: ~/repo
  deployer:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
commands:
  restore_yarn:
    steps:
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-
  save_yarn:
    steps:
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
  persist:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - .
  attach:
    steps:
      - attach_workspace:
          at: .

jobs:
  install:
    executor:
      name: builder
    steps:
      - checkout
      - restore_yarn
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_yarn
      - persist

  test:
    executor:
      name: builder
    steps:
      - attach
      - run:
          name: Test
          command: yarn test

  deploy:
    executor:
      name: deployer
    parameters:
      release_target:
        type: enum
        enum: ["staging", "prduction"]
    steps:
      - attach
      - run:
          name: 'Install Deploy Tools'
          command: |
            pip3 install --upgrade --user awscli
            echo 'export PATH=~/.local/bin:$PATH' > ~/.profile && \
            source ~/.profile && \
            aws configure set preview.cloudfront true
      - run:
          name: Set Env << parameters.release_target >>
          command: |
            TMP_ENV_FILENAME=".env.<< parameters.release_target >>-env"
            echo "" > ${TMP_ENV_FILENAME}
            echo "REACT_APP_BASTET_HOST_URL=${BASTET_HOST_URL}" >> ${TMP_ENV_FILENAME}
            echo "REACT_APP_COGNITO_USER_POOL_ID=${BASTET_HOST_URL}" >> ${TMP_ENV_FILENAME}
            echo "REACT_APP_COGNITO_CLIENT_ID=${BASTET_HOST_URL}" >> ${TMP_ENV_FILENAME}
      - run:
          name: Deploy to << parameters.release_target >>
          command: |
            TMP_SHELL_NAME="deploy-to-<< parameters.release_target >>.sh"
            sh ${TMP_SHELL_NAME}

workflows:
  setup_and_deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - deploy:
          name: deploy_to_staging
          release_target: staging
          context: Bastet-Staging
          requires:
            - install
            - test
          # filters:
          #   branches:
          #     only: developa
      - approval_to_production:
          type: approval
          requires:
            - install
            - test
          filters:
            branches:
              only: master
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}.*/
      - deploy:
          name: deploy_to_prduction
          release_target: prduction
          context: Bastet-Production
          requires:
            - approval_to_production
