export const LOAD_DEVICE_WATERINGS = '@KF/LOAD_DEVICE_WATERINGS';
export const SELECT_DEVICE_WATERINGS = '@KF/SELECT_DEVICE_WATERINGS';
export const LOAD_DEVICE_WATERING_SCHEDULES = '@KF/LOAD_DEVICE_WATERING_SCHEDULES';
export const SAVE_DEVICE_WATERING_SCHEDULES = '@KF/SAVE_DEVICE_WATERING_SCHEDULES';
export const ADD_DEVICE_WATERING_SCHEDULE = '@KF/ADD_DEVICE_WATERING_SCHEDULE';
export const REMOVE_DEVICE_WATERING_SCHEDULE = '@KF/REMOVE_DEVICE_WATERING_SCHEDULE';
export const UPDATE_DEVICE_WATERING_SCHEDULE = '@KF/UPDATE_DEVICE_WATERING_SCHEDULE';
