export const DevicesWatering = {
  LOAD: '@KF/LOAD',
  SELECT: '@KF/SELECT',
  LOAD_SCHEDULES: '@KF/LOAD_SCHEDULES',
  SAVE_SCHEDULES: '@KF/SAVE_SCHEDULES',
  ADD_SCHEDULE: '@KF/ADD_SCHEDULE',
  REMOVE_SCHEDULE: '@KF/REMOVE_SCHEDULE',
  UPDATE_SCHEDULE: '@KF/UPDATE_SCHEDULE',
}
