export const DevicesPyranometer = {
  LOAD_REQUEST: '@KF/LOAD_REQUEST',
  LOAD_SUCCESS: '@KF/LOAD_SUCCESS',
  LOAD_FAILURE: '@KF/LOAD_FAILURE',
  SELECT: '@KF/SELECT',
  LOAD_SENSING_RECORDS_REQUEST: '@KF/LOAD_SENSING_RECORDS_REQUEST',
  LOAD_SENSING_RECORDS_SUCCESS: '@KF/LOAD_SENSING_RECORDS_SUCCESS',
  LOAD_SENSING_RECORDS_FAILURE: '@KF/LOAD_SENSING_RECORDS_FAILURE',
}
