export const Me = {
  RENAME: 'RENAME',
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  CONFIRM_REQUEST: 'CONFIRM_REQUEST',
  CONFIRM_FAILURE: 'CONFIRM_FAILURE',
  CONFIRM_SUCCESS: 'CONFIRM_SUCCESS',
}
